# ============================================================================
# Claude Code SessionStart hook (PowerShell): bootstrap generated agent-core
# config into a fresh git worktree (CLAUDE.md + .claude/rules).
#
# LAUNCHER: `powershell -NoProfile -ExecutionPolicy Bypass -File <this>.ps1`
# (src/targets/claude.ts) - Windows PowerShell 5.1, NOT `pwsh`. There is
# deliberately no shebang: nothing ever execs this file, the old
# `#!/usr/bin/env pwsh` named an interpreter that is not installed on the
# target machines, and since ADR-0027 a UTF-8 BOM precedes the first line in
# the DEPLOYED copy anyway.
#
# 1:1 port of worktree-bootstrap.sh for Windows machines where Claude Code
# routes hook commands through PowerShell (Git Bash optional / absent).
#
# Why this exists: agent-core's per-project config (CLAUDE.md, AGENTS.md, the
# whole .claude/ rules tree) is GENERATED by `agent-core sync` (ADR-0015) and
# is gitignored - so it does NOT come along when you run `git worktree add`.
# A brand-new linked worktree therefore starts with no agent-core config; this
# hook regenerates (or copies) it on first session start.
#
# Worktree detection uses the ".git-is-a-file" trick: in a LINKED worktree the
# git dir (--git-dir) differs from the common git dir (--git-common-dir); in
# the MAIN worktree they are identical.
#
# Receives the session event as JSON on stdin (not evaluated here).
# C:/Users/Anwender/AppData/Local/npm-cache/_npx/0174d06561286187/node_modules/@gmolike/agent-core is replaced by the sync adapter with the absolute
# PKG_ROOT path at install time. This is the Claude-only path.
#
# FAIL-OPEN: this hook must NEVER fail a session - the body is wrapped in
# try/catch and the script always exits 0.
# ============================================================================
$ErrorActionPreference = 'SilentlyContinue'

# --- deterministic UTF-8 I/O, BEFORE anything is read or written ----------------------------------
# The three-line block below is ONE shared form - byte-for-byte the same in every agent-core .ps1 hook
# that decodes non-ASCII text, pinned as such by a lockstep test in src/targets/claude.test.ts. Every
# statement in it is PROCESS-LOCAL: none of them touches the console (ADR-0027 R2).
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
$OutputEncoding = $Utf8NoBom
$StdInUtf8 = New-Object System.IO.StreamReader([Console]::OpenStandardInput(), $Utf8NoBom)

# --- process-local native I/O helpers -------------------------------------------------------------
# The block from ConvertTo-NativeArgument down to the end of Write-Stdout is the SECOND shared form:
# byte-for-byte identical in every hook that reads a native command's stdout or writes its own, and
# pinned by the same lockstep test. THIS hook is the textbook case for it: every path it acts on comes
# out of `git rev-parse` / `git worktree list`, and under the old `(git ... | Out-String)` form those
# were decoded with [Console]::OutputEncoding - so a worktree under C:/Users/Joerg-with-an-umlaut came
# back as CP850 mojibake, Test-Path was False, and the bootstrap silently did nothing. It writes no
# stdout of its own, so Write-Stdout is unused here; the block is carried whole because a partial hand
# copy is exactly how the two forms drift apart.

<#
.SYNOPSIS
Quote one argument the way CommandLineToArgvW parses it back, so a path holding a space or a
backslash reaches the child intact.
.DESCRIPTION
The quoting PowerShell would do for `&` has to be done here, because Invoke-NativeUtf8 hands
Start-Process ONE command-line string. That is deliberate: PowerShell 5.1 joins an -ArgumentList
ARRAY with spaces and quotes nothing, so an array element holding a space silently splits into two
arguments - measured against a repo path holding both a space and U+00FC, git died with "cannot
change to '...\my'". Passing a single, self-quoted string is the only form that survives; with this
quoter the same path arrives intact (Test-Path True).
.PARAMETER Value
The raw argument.
.OUTPUTS
System.String - the argument, quoted only when it has to be.
#>
function ConvertTo-NativeArgument([string]$Value) {
  if ($Value -cmatch '^[A-Za-z0-9_.:/=+@%-]+$') { return $Value }
  $sb = New-Object System.Text.StringBuilder
  [void]$sb.Append('"')
  $slashes = 0
  foreach ($ch in $Value.ToCharArray()) {
    if ($ch -eq '\') { $slashes++; continue }
    if ($ch -eq '"') { [void]$sb.Append('\', ($slashes * 2) + 1); [void]$sb.Append('"'); $slashes = 0; continue }
    if ($slashes -gt 0) { [void]$sb.Append('\', $slashes); $slashes = 0 }
    [void]$sb.Append($ch)
  }
  if ($slashes -gt 0) { [void]$sb.Append('\', $slashes * 2) }
  [void]$sb.Append('"')
  return $sb.ToString()
}

<#
.SYNOPSIS
Run a native command and read its stdout as UTF-8 - PROCESS-LOCALLY, without touching the console.
.DESCRIPTION
Windows PowerShell 5.1 decodes a native command's stdout with [Console]::OutputEncoding, and that
SETTER calls SetConsoleOutputCP - it rewrites the inherited console's code page for every later
process in it. Here every byte goes through a TEMP FILE instead, so nothing but this process is
involved: the child writes raw bytes, and THIS code decides they are UTF-8. Measured on
`git rev-parse --absolute-git-dir` in a repo path holding U+00FC: plain `& git` with the console
left alone -> U+251C U+255D, Test-Path False; `& git` after the old setter -> U+00FC, Test-Path
True, but ConsoleOutputCP moved 850 -> 65001; this helper -> U+00FC, Test-Path True, console
unchanged at 850/850.
FILE redirection, not a pipe, and that is the load-bearing detail. A redirected ProcessStartInfo
pipe hands stdin to a .NET StreamWriter built from [Console]::InputEncoding, whose AutoFlush emits
that encoding's PREAMBLE at Process.Start - before this code writes anything. On a console left at
CP 65001 (a `chcp 65001` terminal is common) that preamble is a UTF-8 BOM: measured, the child read
`efbbbf7b226167656e745f6964...` instead of `7b226167656e745f6964...`, JSON.parse threw, node
answered "unparsable" and the guard flipped from DENY to fail-open ALLOW while the .sh still denied
- one payload, two answers, decided by the user's code page. Start-Process -RedirectStandardInput
opens the file itself, so the child gets exactly the bytes written here: measured identical
(`7b22637764223a22433a2f78227d`) from a console at 850 AND at 65001.
The executable is resolved through Get-Command because Start-Process does not apply PATHEXT to a
bare name the way `&` does (a bare "jq" would miss a jq.cmd shim, which is exactly what the suite
puts on PATH). $proc.Handle is read once because a Start-Process object drops its handle on exit and
ExitCode then reads back empty - and the exit code is what the jq stage and Invoke-Git branch on.
.PARAMETER Command
Command name to resolve on PATH.
.PARAMETER CommandArgs
Arguments, each passed through untouched - no shell is involved, nothing is word-split or expanded.
.PARAMETER StdinText
Optional text written to the child as UTF-8 bytes; '' or $null sends an empty stdin (immediate EOF).
.PARAMETER WorkingDirectory
Optional working directory. Without it PowerShell 5.1 hands the child ITS OWN location rather than
the process directory - measured: after a Push-Location the child reported the pushed path. No
shipped hook uses Push-Location, so the two coincide; the guard passes nothing on purpose and
therefore resolves in the session's directory, the status line passes the payload's cwd.
.OUTPUTS
System.Collections.Hashtable - @{ ExitCode = <int>; Stdout = <string> }, or $null when the command
could not be resolved, started or read.
#>
function Invoke-NativeUtf8([string]$Command, [string[]]$CommandArgs, [string]$StdinText, [string]$WorkingDirectory) {
  $exe = @(Get-Command $Command -CommandType Application -ErrorAction SilentlyContinue)[0]
  if (-not $exe) { return $null }
  $inFile = [IO.Path]::GetTempFileName()
  $outFile = [IO.Path]::GetTempFileName()
  $errFile = [IO.Path]::GetTempFileName()
  try {
    [IO.File]::WriteAllBytes($inFile, $Utf8NoBom.GetBytes([string]$StdinText))
    $spawn = @{
      FilePath               = $exe.Source
      NoNewWindow            = $true
      PassThru               = $true
      ErrorAction            = 'SilentlyContinue'
      RedirectStandardInput  = $inFile
      RedirectStandardOutput = $outFile
      RedirectStandardError  = $errFile
    }
    $argLine = (@($CommandArgs | ForEach-Object { ConvertTo-NativeArgument $_ }) -join ' ')
    if ($argLine) { $spawn['ArgumentList'] = $argLine }
    if ($WorkingDirectory) { $spawn['WorkingDirectory'] = $WorkingDirectory }
    $proc = Start-Process @spawn
    if (-not $proc) { return $null }
    $null = $proc.Handle
    $proc.WaitForExit()
    return @{ ExitCode = $proc.ExitCode; Stdout = [IO.File]::ReadAllText($outFile, $Utf8NoBom) }
  }
  catch { return $null }
  finally { Remove-Item -LiteralPath $inFile, $outFile, $errFile -Force -ErrorAction SilentlyContinue }
}

<#
.SYNOPSIS
Split a native command's stdout into lines the way PowerShell's OWN native-output enumeration did:
one trailing newline terminates the last line, it does not add an empty one.
.DESCRIPTION
Keeping that rule in one place is what makes the move off `& command` a mechanical 1:1 port - every
call site below reads `$lines[0]` / `-join` exactly as it did when PowerShell produced the array.
.PARAMETER Text
Raw stdout as returned by Invoke-NativeUtf8.
.OUTPUTS
System.String[] - the lines; an empty array when the command printed nothing.
#>
function ConvertTo-NativeLines([string]$Text) {
  if (-not $Text) { return , @() }
  return , @(($Text -creplace '\r?\n$', '') -split '\r?\n')
}

<#
.SYNOPSIS
Write text to stdout as raw UTF-8 bytes, bypassing [Console]::Out and its code page entirely.
.PARAMETER Text
The already-assembled output - a JSON envelope, or the status line.
.OUTPUTS
None. Writes bytes to the standard output stream.
#>
function Write-Stdout([string]$Text) {
  $bytes = $Utf8NoBom.GetBytes($Text)
  $stream = [Console]::OpenStandardOutput()
  $stream.Write($bytes, 0, $bytes.Length)
  $stream.Flush()
}

<#
.SYNOPSIS
First stdout line of a git command, decoded as UTF-8 per CHILD process.
.DESCRIPTION
The 1:1 replacement for the old `(git ... 2>$null | Out-String).Trim()` form: same result on ASCII
input, correct result on a path holding a non-ASCII character, and no console involved either way.
A non-zero exit or an unresolvable git yields '' - which every call site below already treats as
"not a repo / nothing to do", so the fail-open behaviour is unchanged.
.PARAMETER GitArgs
Arguments for git, each passed through untouched.
.OUTPUTS
System.String - the first line of stdout, trimmed; '' when git failed or printed nothing.
#>
function Get-GitLine([string[]]$GitArgs) {
  $run = Invoke-NativeUtf8 'git' $GitArgs
  if (-not $run -or $run.ExitCode -ne 0) { return '' }
  return ([string](@(ConvertTo-NativeLines $run.Stdout)[0])).Trim()
}

# Drain stdin (Claude Code convention; not evaluated here) - through the prologue's reader, never
# [Console]::In, so the drain cannot fail on a payload byte the console code page has no mapping for.
[void]$StdInUtf8.ReadToEnd()

try {
    # --- Detect a linked git worktree ---------------------------------------
    # In the main worktree --git-dir == --git-common-dir; in a linked worktree
    # they differ. Empty means "not a git repo" - nothing to bootstrap.
    $gitdir = Get-GitLine @('rev-parse', '--git-dir')
    $common = Get-GitLine @('rev-parse', '--git-common-dir')
    if (-not $gitdir -or -not $common) { exit 0 }
    if ($gitdir -eq $common) {
        # Main worktree - nothing to do.
        exit 0
    }

    # --- This is a linked worktree ------------------------------------------
    $top = Get-GitLine @('rev-parse', '--show-toplevel')
    if (-not $top) { exit 0 }
    if (Test-Path -LiteralPath (Join-Path $top 'CLAUDE.md')) {
        # Config already present in this worktree - nothing to bootstrap.
        exit 0
    }

    # --- Config missing -> bootstrap ----------------------------------------
    # Strategy - try in order, all output suppressed, never fail the session:
    #   a. agent-core on PATH  ->  regenerate config in-place for this worktree
    #   b. node dist/cli.js    ->  same, via the baked-in PKG_ROOT path
    #   c. copy from primary   ->  locked-down env (no npm/token), or a/b left
    #                              CLAUDE.md still absent: mirror the main worktree
    $agentCore = Get-Command agent-core -ErrorAction SilentlyContinue
    $cliPath = "C:/Users/Anwender/AppData/Local/npm-cache/_npx/0174d06561286187/node_modules/@gmolike/agent-core/dist/cli.js"
    if ($agentCore) {
        Push-Location $top
        try { agent-core sync --scope project 2>$null | Out-Null } catch {} finally { Pop-Location }
    } elseif (Test-Path -LiteralPath $cliPath) {
        Push-Location $top
        try { node $cliPath sync --scope project 2>$null | Out-Null } catch {} finally { Pop-Location }
    }

    # Fallback: if config is still missing, copy it from the primary worktree.
    # `git worktree list --porcelain` lists worktrees; the FIRST `worktree
    # <path>` line is the main worktree. Read as UTF-8 per child, because that
    # path is exactly the one that used to arrive as mojibake.
    if (-not (Test-Path -LiteralPath (Join-Path $top 'CLAUDE.md'))) {
        $main = $null
        $listRun = Invoke-NativeUtf8 'git' @('worktree', 'list', '--porcelain')
        $lines = if ($listRun -and $listRun.ExitCode -eq 0) { ConvertTo-NativeLines $listRun.Stdout } else { @() }
        foreach ($line in $lines) {
            if ($line -match '^worktree (.+)$') { $main = $Matches[1].Trim(); break }
        }
        if ($main -and ($main -ne $top) -and (Test-Path -LiteralPath (Join-Path $main 'CLAUDE.md'))) {
            try { Copy-Item -LiteralPath (Join-Path $main 'CLAUDE.md') -Destination (Join-Path $top 'CLAUDE.md') -Recurse -Force 2>$null } catch {}
            $mainAgents = Join-Path $main 'AGENTS.md'
            if (Test-Path -LiteralPath $mainAgents) {
                try { Copy-Item -LiteralPath $mainAgents -Destination (Join-Path $top 'AGENTS.md') -Recurse -Force 2>$null } catch {}
            }
            $mainClaude = Join-Path $main '.claude'
            if (Test-Path -LiteralPath $mainClaude) {
                try { Copy-Item -LiteralPath $mainClaude -Destination $top -Recurse -Force 2>$null } catch {}
            }
        }
    }
} catch {
    # Fail-open: never let a bootstrap error break the session.
}

exit 0
