#!/usr/bin/env pwsh
# ============================================================================
# Claude Code SessionStart hook (PowerShell): bootstrap generated agent-core
# config into a fresh git worktree (CLAUDE.md + .claude/rules).
#
# 1:1 port of worktree-bootstrap.sh for Windows machines where Claude Code
# routes hook commands through PowerShell (Git Bash optional / absent).
#
# Why this exists: agent-core's per-project config (CLAUDE.md, AGENTS.md, the
# whole .claude/ rules tree) is GENERATED by `agent-core sync` (ADR-0015) and
# is gitignored — so it does NOT come along when you run `git worktree add`.
# A brand-new linked worktree therefore starts with no agent-core config; this
# hook regenerates (or copies) it on first session start.
#
# Worktree detection uses the ".git-is-a-file" trick: in a LINKED worktree the
# git dir (--git-dir) differs from the common git dir (--git-common-dir); in
# the MAIN worktree they are identical.
#
# Receives the session event as JSON on stdin (not evaluated here).
# C:/Entwicklung/claude-skills is replaced by the sync adapter with the absolute
# PKG_ROOT path at install time. This is the Claude-only path.
#
# FAIL-OPEN: this hook must NEVER fail a session — the body is wrapped in
# try/catch and the script always exits 0.
# ============================================================================
$ErrorActionPreference = 'SilentlyContinue'

# Drain stdin (Claude Code convention; not evaluated here).
[void][Console]::In.ReadToEnd()

try {
    # --- Detect a linked git worktree ---------------------------------------
    # In the main worktree --git-dir == --git-common-dir; in a linked worktree
    # they differ. Empty means "not a git repo" — nothing to bootstrap.
    $gitdir = (git rev-parse --git-dir 2>$null | Out-String).Trim()
    $common = (git rev-parse --git-common-dir 2>$null | Out-String).Trim()
    if (-not $gitdir -or -not $common) { exit 0 }
    if ($gitdir -eq $common) {
        # Main worktree — nothing to do.
        exit 0
    }

    # --- This is a linked worktree ------------------------------------------
    $top = (git rev-parse --show-toplevel 2>$null | Out-String).Trim()
    if (-not $top) { exit 0 }
    if (Test-Path -LiteralPath (Join-Path $top 'CLAUDE.md')) {
        # Config already present in this worktree — nothing to bootstrap.
        exit 0
    }

    # --- Config missing → bootstrap -----------------------------------------
    # Strategy — try in order, all output suppressed, never fail the session:
    #   a. agent-core on PATH  →  regenerate config in-place for this worktree
    #   b. node dist/cli.js    →  same, via the baked-in PKG_ROOT path
    #   c. copy from primary   →  locked-down env (no npm/token), or a/b left
    #                             CLAUDE.md still absent: mirror the main worktree
    $agentCore = Get-Command agent-core -ErrorAction SilentlyContinue
    $cliPath = "C:/Entwicklung/claude-skills/dist/cli.js"
    if ($agentCore) {
        Push-Location $top
        try { agent-core sync --scope project 2>$null | Out-Null } catch {} finally { Pop-Location }
    } elseif (Test-Path -LiteralPath $cliPath) {
        Push-Location $top
        try { node $cliPath sync --scope project 2>$null | Out-Null } catch {} finally { Pop-Location }
    }

    # Fallback: if config is still missing, copy it from the primary worktree.
    # `git worktree list --porcelain` lists worktrees; the FIRST `worktree
    # <path>` line is the main worktree.
    if (-not (Test-Path -LiteralPath (Join-Path $top 'CLAUDE.md'))) {
        $main = $null
        $lines = git worktree list --porcelain 2>$null
        foreach ($line in $lines) {
            if ($line -match '^worktree (.+)$') { $main = $Matches[1].Trim(); break }
        }
        if ($main -and ($main -ne $top) -and (Test-Path -LiteralPath (Join-Path $main 'CLAUDE.md'))) {
            try { Copy-Item -LiteralPath (Join-Path $main 'CLAUDE.md') -Destination (Join-Path $top 'CLAUDE.md') -Recurse -Force 2>$null } catch {}
            $mainAgents = Join-Path $main 'AGENTS.md'
            if (Test-Path -LiteralPath $mainAgents) {
                try { Copy-Item -LiteralPath $mainAgents -Destination (Join-Path $top 'AGENTS.md') -Recurse -Force 2>$null } catch {}
            }
            $mainClaude = Join-Path $main '.claude'
            if (Test-Path -LiteralPath $mainClaude) {
                try { Copy-Item -LiteralPath $mainClaude -Destination $top -Recurse -Force 2>$null } catch {}
            }
        }
    }
} catch {
    # Fail-open: never let a bootstrap error break the session.
}

exit 0
