#!/usr/bin/env bash
# Claude Code SessionStart hook: bootstrap generated agent-core config into a
# fresh git worktree (CLAUDE.md + .claude/rules).
#
# Why this exists: agent-core's per-project config (CLAUDE.md, AGENTS.md, the
# whole .claude/ rules tree) is GENERATED by `agent-core sync` (ADR-0015) and
# is gitignored — so it is NOT tracked and does NOT come along when you run
# `git worktree add`. A brand-new linked worktree therefore starts life with no
# agent-core config at all; this hook regenerates (or copies) it on first
# session start so every worktree behaves like the primary checkout.
#
# Worktree detection uses the ".git-is-a-file" trick: in a LINKED worktree the
# git dir (`--git-dir`) differs from the common git dir (`--git-common-dir`),
# whereas in the MAIN worktree they are identical. If they match (or we are not
# in a repo at all) there is nothing to bootstrap.
#
# Receives the session event as JSON on stdin (Claude Code convention; not
# evaluated here). C:/Users/Anwender/AppData/Local/npm-cache/_npx/0e26d8a440c77845/node_modules/@gmolike/agent-core is replaced by the sync adapter with the
# absolute PKG_ROOT path at install time, so the node fallback never depends on
# CWD. This is the Claude-only path — OpenCode has no 1:1 session-startup hook.
#
# FAIL-OPEN: this hook must NEVER fail a session — every step is guarded and the
# script always exits 0.
set -euo pipefail

# --- Detect a linked git worktree -------------------------------------------
# In the main worktree --git-dir == --git-common-dir; in a linked worktree they
# differ. Empty means "not a git repo" — nothing to bootstrap either way.
_gitdir="$(git rev-parse --git-dir 2>/dev/null || true)"
_common="$(git rev-parse --git-common-dir 2>/dev/null || true)"
if [ -z "$_gitdir" ] || [ -z "$_common" ]; then
  exit 0
fi
if [ "$_gitdir" = "$_common" ]; then
  # Main worktree — its config is generated/tracked normally, nothing to do.
  exit 0
fi

# --- This is a linked worktree ----------------------------------------------
_top="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$_top" ]; then
  exit 0
fi
if [ -f "$_top/CLAUDE.md" ]; then
  # Config already present in this worktree — nothing to bootstrap.
  exit 0
fi

# --- Config missing → bootstrap ---------------------------------------------
# Strategy — try in order, all output to /dev/null, never fail the session:
#   a. agent-core on PATH  →  regenerate config in-place for this worktree
#   b. node dist/cli.js    →  same, via the baked-in PKG_ROOT path
#   c. copy from primary   →  locked-down env (no npm/token), or a/b left
#                             CLAUDE.md still absent: mirror the main worktree
if command -v agent-core >/dev/null 2>&1; then
  ( cd "$_top" && agent-core sync --scope project >/dev/null 2>&1 || true )
elif [ -f "C:/Users/Anwender/AppData/Local/npm-cache/_npx/0e26d8a440c77845/node_modules/@gmolike/agent-core/dist/cli.js" ]; then
  ( cd "$_top" && node "C:/Users/Anwender/AppData/Local/npm-cache/_npx/0e26d8a440c77845/node_modules/@gmolike/agent-core/dist/cli.js" sync --scope project >/dev/null 2>&1 || true )
fi

# Fallback: if config is still missing, copy it from the primary worktree.
# `git worktree list --porcelain` lists worktrees; the FIRST `worktree <path>`
# line is the main worktree.
if [ ! -f "$_top/CLAUDE.md" ]; then
  _main="$(git worktree list --porcelain 2>/dev/null | awk '/^worktree /{print substr($0, 10); exit}' || true)"
  if [ -n "$_main" ] && [ "$_main" != "$_top" ] && [ -f "$_main/CLAUDE.md" ]; then
    cp -R "$_main/CLAUDE.md" "$_top/CLAUDE.md" >/dev/null 2>&1 || true
    if [ -f "$_main/AGENTS.md" ]; then
      cp -R "$_main/AGENTS.md" "$_top/AGENTS.md" >/dev/null 2>&1 || true
    fi
    if [ -d "$_main/.claude" ]; then
      cp -R "$_main/.claude" "$_top/" >/dev/null 2>&1 || true
    fi
  fi
fi

exit 0
